# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
    args: [--allow-multiple-documents]
  - id: check-xml
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-symlinks
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.11.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix]
- repo: https://github.com/cheshirekow/cmake-format-precommit
  rev: v0.6.13
  hooks:
  - id: cmake-format
  - id: cmake-lint
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v17.0.6
  hooks:
  - id: clang-format
    types_or: [c++, c, objective-c, json]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910
  hooks:
  - id: mypy
    args: [--ignore-missing-imports, --follow-imports=skip]
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.1.6
  hooks:
          # Run the linter.
  - id: ruff
          # Run the formatter.
  - id: ruff-format
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.27.2
  hooks:
  - id: check-github-workflows
    args: [--verbose]
  - id: check-github-actions
    args: [--verbose]
